### ISSUE TITLE
Mesh bed leveling

### ISSUE THREAD

**Issue by TomyVertigo** [Ultimaker/UM2.1-Firmware#14]
Looks like there is no option to engage mesh bed leveling. Can you please check?

**Comment by 1010011011** [comment]
I just have this and when I select **BUILD-PLATE** in this menu, it starts the wizard. Under advanced, there's nothing you refer to.

```
void lcd_menu_maintenance()
{
    lcd_tripple_menu(PSTR("BUILD-|PLATE"), PSTR("ADVANCED"), PSTR("RETURN"));

    if (lcd_lib_button_pressed)
    {
        if (IS_SELECTED_MAIN(0))
            lcd_change_to_menu(lcd_menu_first_run_start_bed_leveling);
        else if (IS_SELECTED_MAIN(1))
            lcd_change_to_menu(lcd_menu_maintenance_advanced);
        else if (IS_SELECTED_MAIN(2))
            lcd_change_to_menu(lcd_menu_main);
    }

    lcd_lib_update_screen();
}

static char* lcd_advanced_item(uint8_t nr)
{
    if (nr == 0)
        strcpy_P(card.longFilename, PSTR("< RETURN"));
    else if (nr == 1)
        strcpy_P(card.longFilename, PSTR("LED settings"));
    else if (nr == 2)
#if EXTRUDERS < 2
        strcpy_P(card.longFilename, PSTR("Heatup nozzle"));
#else
        strcpy_P(card.longFilename, PSTR("Heatup first nozzle"));
    else if (nr == 3)
        strcpy_P(card.longFilename, PSTR("Heatup second nozzle"));
#endif
#if TEMP_SENSOR_BED != 0
    else if (nr == 2 + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Heatup buildplate"));
#endif
    else if (nr == 2 + BED_MENU_OFFSET + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Home head"));
    else if (nr == 3 + BED_MENU_OFFSET + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Lower buildplate"));
    else if (nr == 4 + BED_MENU_OFFSET + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Raise buildplate"));
    else if (nr == 5 + BED_MENU_OFFSET + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Insert material"));
    else if (nr == 6 + BED_MENU_OFFSET + EXTRUDERS)
#if EXTRUDERS < 2
        strcpy_P(card.longFilename, PSTR("Move material"));
#else
        strcpy_P(card.longFilename, PSTR("Move material (1)"));
    else if (nr == 7 + BED_MENU_OFFSET + EXTRUDERS)
        strcpy_P(card.longFilename, PSTR("Move material (2)"));
#endif
    else if (nr == 6 + BED_MENU_OFFSET + EXTRUDERS * 2)
        strcpy_P(card.longFilename, PSTR("Set fan speed"));
    else if (nr == 7 + BED_MENU_OFFSET + EXTRUDERS * 2)
        strcpy_P(card.longFilename, PSTR("Motion settings"));
    else if (nr == 8 + BED_MENU_OFFSET + EXTRUDERS * 2)
        strcpy_P(card.longFilename, PSTR("Version"));
    else if (nr == 9 + BED_MENU_OFFSET + EXTRUDERS * 2)
        strcpy_P(card.longFilename, PSTR("Runtime stats"));
    else if (nr == 10 + BED_MENU_OFFSET + EXTRUDERS * 2)
        strcpy_P(card.longFilename, PSTR("Factory reset"));
    else
        strcpy_P(card.longFilename, PSTR("???"));
    return card.longFilename;
}
```

When calibrating the bed-level it starts the wizard. I don't see any option to create a MESH.
_Maybe I'm looking in the wrong place._ 

P.S. I don't see an advantage except for tho possibility of a remote auto bed-level with a sensor, but even then I would prefer the screw ajust over a Z-axis dynamic ajust. Assuming you visit your printer from time to time.

```
//Started bed leveling from the calibration menu
void lcd_menu_first_run_start_bed_leveling()
{
    lcd_question_screen(lcd_menu_first_run_bed_level_center_adjust, homeAndParkHeadForCenterAdjustment2, PSTR("CONTINUE"), lcd_menu_main, NULL, PSTR("CANCEL"));
    lcd_lib_draw_string_centerP(10, PSTR("I will guide you"));
    lcd_lib_draw_string_centerP(20, PSTR("through the process"));
    lcd_lib_draw_string_centerP(30, PSTR("of adjusting your"));
    lcd_lib_draw_string_centerP(40, PSTR("buildplate."));
    lcd_lib_update_screen();
}

static void homeAndRaiseBed()
{
    enquecommand_P(PSTR("G28 Z0"));
    char buffer[32];
    sprintf_P(buffer, PSTR("G1 F%i Z%i"), int(homing_feedrate[0]), 35);
    enquecommand(buffer);
}

etc... etc... 
```

During this routine it refers to the screws. At the end is saved the value of the Z-axis. If you have two extruders there is an option to set a difference in height. Please show me where you got the code from, or what I have missed.

Greetinx,
1010011011
(Just a user of this code, so I could be completely WRONG HERE !!!)...

**Comment by TomyVertigo** [comment]
Hello,

in original Merlin FW there is a MESH bed leveling option. Since I've upgraded my heat bed there is a problem with high temperature, when the table is not completely flat anymore and this is an excellent option to get a perfect first layer. That is especially important for more tricky materials as PC.

Example of missing code:
//#define AUTO_BED_LEVELING_3POINT
//#define AUTO_BED_LEVELING_LINEAR
//#define AUTO_BED_LEVELING_BILINEAR
//#define AUTO_BED_LEVELING_UBL
//#define MESH_BED_LEVELING

/**
 * Normally G28 leaves leveling disabled on completion. Enable
 * this option to have G28 restore the prior leveling state.
 */
//#define RESTORE_LEVELING_AFTER_G28

/**
 * Enable detailed logging of G28, G29, M48, etc.
 * Turn on with the command 'M111 S32'.
 * NOTE: Requires a lot of PROGMEM!
 */
//#define DEBUG_LEVELING_FEATURE

#if ANY(MESH_BED_LEVELING, AUTO_BED_LEVELING_BILINEAR, AUTO_BED_LEVELING_UBL)
  // Gradually reduce leveling correction until a set height is reached,
  // at which point movement will be level to the machine's XY plane.
  // The height can be set with M420 Z<height>
  #define ENABLE_LEVELING_FADE_HEIGHT

  // For Cartesian machines, instead of dividing moves on mesh boundaries,
  // split up moves into short segments like a Delta. This follows the
  // contours of the bed more closely than edge-to-edge straight moves.
  #define SEGMENT_LEVELED_MOVES
  #define LEVELED_SEGMENT_LENGTH 5.0 // (mm) Length of all segments (except the last one)

Source: https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.0.x/config/examples/UltiMachine/Archim1/Configuration.h


Greetinx 2u2  👍 
Tomy

**Comment by 1010011011** [comment]
**Ah, ok...**

MESH bed leveling is in the original code, because it's a blank for any sort of printer, but this code is for an Ultimaker 2. The size of the bed and its design is pretty much fixed and doesn't give much room for changes.

_**OFF TOPIC (bit on topic) advice:**_
Maybe you have already done so, but I advise you to solve your problem with a 2-step preheating of the bed with a long pause before heating the nozzle (CODE might be interesting if target temperature > set value that problems occure) and...

_building an enclosure, to prevent extreme temperature differences of the bed. I assume you haven't changed the length of thermistor, because in case of a 2 wire system that changes the reading. Calibrating might be an idea._

If a manual test gives good results, BED_INTERMEDIATETEMP (sounds good) could be a first goal if the target is over the trigger value. When TRUE the BED_MAXTEMP can be the next goal and eventually SOFT PWM and OFF. SCOPE it so the BED_INTERMEDIATETEMP doesn't play a role anymore in case the values are close together. You don't want to end up in step 1 cool down in the middle of you print.

	  if((current_temperature_bed > BED_MINTEMP) && (current_temperature_bed < BED_MAXTEMP))
	  {
	    soft_pwm_bed = (int)pid_output >> 1;
	  }
	  else {
	    soft_pwm_bed = 0;
	  }


**Greetinx and have fun,
1010011011**

**Comment by TomyVertigo** [comment]
1010011011 thank you very much for your support, but I would really like to implement mesh bed leveling. I have it on my UMO and absolutely love it.

Do you have any idea how to do this?

**Comment by Ghostkeeper** [comment]
The Ultimaker2.1 Marlin version was [forked off](https://github.com/Ultimaker/UM2.1-Firmware/commit/ac6463e0e469d8620439e8e4bbc2ba2ec8941a45) from the mainline Marlin repository in June 2013. Mesh Bed Levelling was implemented in [March 2015](https://github.com/MarlinFirmware/Marlin/commit/0e51e53813c3f2ccd64e09c2cbc16c2740b3974c) in mainline Marlin. As such there is no mesh bed levelling in this Marlin version. It won't get added either. Sorry!
