### ISSUE TITLE
coolingfans only goes to 14%

### ISSUE THREAD

**Issue by Juumpa** [Ultimaker/UM2.1-Firmware#15]
updated my 2+ extended and now the coolingfans only goes to 14% after first layer.
Got Cura and the profile set to 100%

**Comment by Ghostkeeper** [comment]
Is that visible in the g-code, or is the problem that the Ultimaker 2+ isn't properly executing the fan speed as mentioned in the g-code?

**Comment by Juumpa** [comment]
g-code was fine, but the machine would go to 14% fan speed.
I installed the firmware then reset the printer, tried resetting it again but that did not help.
I'm now using the newest firmware from cura, and the fan works fine

**Comment by Ghostkeeper** [comment]
Maybe that was something in the material profile then. Glad that the firmware update fixed it!
